version: '3.9'

services:
  db:
    image: mysql:8.0
    ports:
      - "3366:3306"
    environment:
      MYSQL_DATABASE: 'teste_docker'
      MYSQL_USER: 'teste'
      MYSQL_PASSWORD: 'teste'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_HOST: 'localhost'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 10s
      retries: 10

  web:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db